### PR TITLE
Add Security Policy and Version

### PR DESCRIPTION
**Pull request by tjrgg**
## Pull Request

- [x] I have read the [Contributing Guidelines](https://github.com/typicalbot/typicalbot/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked the PRs for upcoming features and fixes.

### Changes

- [ ] Internal code
- [x] Documentation
- [x] Other: Added version file

Issues: NaN

### Description

Adds a version file and introduces a security policy. Edits and feedback encouraged.

### CODE REVIEW

**Comment by nsylke** [comment]
What is the point of the versions file? I'm not entirely sure why it's needed.

**Comment by tjrgg** [comment]
> What is the point of the versions file? I'm not entirely sure why it's needed.

I didn't find anywhere else where a version could easily be found, so in order to identify the version, I added the version file. This makes it easier to reference particular versions later and give people and easy way to identify what version they are using.

**Comment by nsylke** [comment]
> 
> 
> > What is the point of the versions file? I'm not entirely sure why it's needed.
> 
> I didn't find anywhere else where a version could easily be found, so in order to identify the version, I added the version file. This makes it easier to reference particular versions later and give people an easy way to identify what version they are using.

Alright, so the current version can be found in the [gradle build script](https://github.com/typicalbot/typicalbot/blob/master/build.gradle.kts#L14). Unfortunately, at this point in stage, that is the only place it can be found. However, once we start using [GitHub's Release](https://github.com/typicalbot/typicalbot/releases) feature, they'll be labeled with the version and we'll add a badge to our read me file. With that being said, do you still believe that this file is necessary?

**Comment by tjrgg** [comment]
As a developer, no. However, from a user's perspective (more specifically, a self-hosting user), I think it might be easier for them to easily identify which version they are running. The easier we are able to make the version available to them, the less headaches for everybody involved. While I think using GitHub Releases and having a badge in the README are good things to do, neither one will help a user quickly identify their version after they've downloaded the bot.

I know the bot has a command that will report the version, but it's also important for a user to be able to identify the version they are using when the bot isn't running, in case there are problems that prevent the user from being able to successfully run the bot.

**Pull request merged**
