### PR TITLE
refactor: remove strings for eval command

### LINKED ISSUE #305: Remove eval localization
### Description

Remove translations for eval command

### Usefulness

As a system command, this doesn't need to be localized.

### Have You...?
- [x] I have checked previous issues to see if my enhancement or feature has already been suggested.
- [x] I have checked previous issues and pull requests to see if my enhancement or feature has already been completed for an upcoming release.

### PR DESCRIPTION
**Pull request by nsylke**
### Items Changed

- [x] Commands
- [ ] Events
- [ ] Handlers
- [ ] Structures
- [ ] Tasks
- [ ] Documentation
- [ ] Other: ______

### Description

Remove strings from eval command

### Issues

Closes #305 

### Have You...?

- [x] I have read the [Contributing Guidelines](https://github.com/typicalbot/typicalbot/blob/master/.github/CONTRIBUTING.md).
- [x] I have completed the [pull request template](https://github.com/typicalbot/typicalbot/blob/master/.github/PULL_REQUEST_TEMPLATE.md).
- [x] I have checked open [pull requests](https://github.com/typicalbot/typicalbot/pulls) for upcoming features and fixes.

### CODE REVIEW

**Comment by nsylke** [comment]
Blocked by #309

**Review by Skillz4Killz — APPROVED** [review]
LGTM! Just quick question what about the eval strings in other languages? Will those be removed automatically somehow?

**Comment by nsylke** [comment]
> LGTM! Just quick question what about the eval strings in other languages? Will those be removed automatically somehow?

Yes, they will be removed once we rebuild strings in crowdin.

**Comment by tjrgg** [comment]
As I said in #305, I'd prefer to see all commands be localized, system or not. It may not provide much benefit to us in the hosted bot, but there could be benefits to system commands being localized for those running their own for development or otherwise. I personally don't see the harm and I also think it makes command consistent.

**Pull request merged**
