### PR TITLE
Replace joke library with icanhazdadjoke API

### PR DESCRIPTION
**Pull request by nsylke**
### Items Changed

- [X] Commands
- [ ] Events
- [ ] Handlers
- [ ] Structures
- [ ] Tasks
- [ ] Documentation
- [ ] Other: ______

### Description

Replace joke library with [icanhazdadjoke](https://icanhazdadjoke.com/api) API.

### Have You...?

- [X] I have read the [Contributing Guidelines](https://github.com/typicalbot/typicalbot/blob/master/.github/CONTRIBUTING.md).
- [X] I have completed the [pull request template](https://github.com/typicalbot/typicalbot/blob/master/.github/PULL_REQUEST_TEMPLATE.md).
- [X] I have checked open [pull requests](https://github.com/typicalbot/typicalbot/pulls) for upcoming features and fixes.

### CODE REVIEW

**Review by bwpikaard — APPROVED** [review]

**Comment by tjrgg** [comment]
Is this library just for dad jokes? I'd prefer the joke command to encompass a variety of jokes, not just jokes of a particular type.

**Comment by nsylke** [comment]
> 
> 
> Is this library just for dad jokes? I'd prefer the joke command to encompass a variety of jokes, not just jokes of a particular type.

I don't believe so, although don't quote me on that. Personally, it would be quite hard to find another public API. Another solution is to run our own API, but we would need to moderate the jokes.

**Comment by tjrgg** [comment]
Blocked to consider an internal API and/or other options.

**Comment by nsylke** [comment]
Will not be continuing from our poll hosted in TypicalBot Lounge. We will be looking at our own solution for the future.

**Pull request closed without merging**
